services:
  backend:
    image: ljurca/assignment11-backend:latest
    container_name: assignment11-backend

  frontend:
    image: ljurca/assignment11-frontend:latest
    container_name: assignment11-frontend

  nginx:
    image: ljurca/assignment11-nginx:latest
    container_name: assignment11-nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
