services:
  backend:
    build: ./backend
    container_name: assignment11-backend

  frontend:
    build: ./frontend
    container_name: assignment11-frontend

  nginx:
    build: ./nginx
    container_name: assignment11-nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
